version: '3'

networks:
  chat_system_network:

volumes:
  development_db_volume:
  test_db_volume:
  rails_bundle:
  redis_volume:
  elasticsearch_volume:

services:
  development_db:
    container_name: chat_system_development_db
    image: mysql:5.7
    volumes:
      - development_db_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat_system_development
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: password
    networks:
      - chat_system_network

  test_db:
    container_name: chat_system_test_db
    image: mysql:5.7
    volumes:
      - test_db_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: chat_system_test
      MYSQL_USERNAME: user
      MYSQL_PASSWORD: password
    networks:
      - chat_system_network

  app:
    container_name: chat_system
    hostname: chat_system
    image: chat_system
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    depends_on:
      - development_db
      - test_db
      - redis
      - elasticsearch
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_HOST: development_db
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTIC_SEARCH_HOST: elasticsearch
    command: ["bundle", "exec", "rails", "server", "-b", "0.0.0.0", "-e", "development"]
    volumes:
      - ./:/app:cached
      - rails_bundle:/bundle
    networks:
      - chat_system_network

  redis:
    container_name: chat_system_redis
    image: redis:7-alpine
    command: redis-server
    volumes:
      - redis_volume:/data
    networks:
      - chat_system_network

  sidekiq:
    container_name: chat_system_sidekiq
    command: bundle exec sidekiq
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    environment:
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_HOST: development_db
      DB_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTIC_SEARCH_HOST: elasticsearch
    depends_on:
      - development_db
      - test_db
      - redis
      - elasticsearch
    networks:
      - chat_system_network

  elasticsearch:
    container_name: chat_system_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.16
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      # ES_JAVA_OPTS environment variable to manually set the heap size to 512MB. We do not recommend using ES_JAVA_OPTS in production
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - elasticsearch_volume:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - chat_system_network
